services:
  # A Docker web service
  - type: web
    name: frontend
    runtime: docker
    repo: https://github.com/dung060103/frontend-todo-app.git # optional
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter instance type)
    branch: master # optional (defaults to master)
    rootDir: frontend
    dockerCommand: ./frontend.sh # optional (defaults to Dockerfile command)
    numInstances: 3 # optional (defaults to 1)
    healthCheckPath: /
    # A Docker web service
  - type: web
    name: backend
    runtime: docker
    repo: https://github.com/dung060103/backend-todo-app.git # optional
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter instance type)
    branch: master # optional (defaults to master)
    rootDir: backend
    dockerCommand: ./backend.sh # optional (defaults to Dockerfile command)
    numInstances: 3 # optional (defaults to 1)
    healthCheckPath: /
